# SPDX-License-Identifier: GPL-2.0
# Standalone build of the binderfs test: make -C tools/testing/selftests/kcov_dataflow/binderfs
TEST_GEN_PROGS := binderfs_test
CFLAGS += -Wall -O2 $(KHDR_INCLUDES)
include ../../lib.mk
