# SPDX-License-Identifier: GPL-2.0
# Standalone build of the ioctl test: make -C tools/testing/selftests/kcov_dataflow/user_ioctl
TEST_GEN_PROGS := user_ioctl
CFLAGS += -Wall -O2 $(KHDR_INCLUDES)
include ../../lib.mk
