# SPDX-License-Identifier: GPL-2.0
TEST_GEN_PROGS := user_ioctl/user_ioctl
TEST_PROGS := run_rust_ffi_contract.sh run_binderfs.sh run_eight_struct_args_c.sh run_eight_struct_args_rust.sh run_rust_kworker_remote.sh
include ../lib.mk
